[Sat Jan 17 17:03:58 2009] [notice] SELinux policy enabled; httpd running as context root:system_r:unconfined_t:SystemLow-SystemHigh
[Sat Jan 17 17:03:58 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Sat Jan 17 17:03:58 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Sat Jan 17 17:03:58 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Sat Jan 17 17:03:58 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Sat Jan 17 17:03:58 2009] [notice] mod_python: using mutex_directory /tmp 
[Sat Jan 17 17:03:58 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Sat Jan 17 17:03:59 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Sat Jan 17 17:07:26 2009] [notice] caught SIGTERM, shutting down
[Sat Jan 17 17:07:29 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Sat Jan 17 17:07:29 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Sat Jan 17 17:07:29 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Sat Jan 17 17:07:29 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Sat Jan 17 17:07:29 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Sat Jan 17 17:07:29 2009] [notice] mod_python: using mutex_directory /tmp 
[Sat Jan 17 17:07:29 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Sat Jan 17 17:07:30 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Sat Jan 17 17:08:45 2009] [notice] caught SIGTERM, shutting down
[Sat Jan 17 17:08:48 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Sat Jan 17 17:08:48 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Sat Jan 17 17:08:48 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Sat Jan 17 17:08:48 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Sat Jan 17 17:08:48 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Sat Jan 17 17:08:48 2009] [notice] mod_python: using mutex_directory /tmp 
[Sat Jan 17 17:08:48 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Sat Jan 17 17:08:49 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Sun Jan 18 01:04:46 2009] [notice] caught SIGTERM, shutting down
[Sun Jan 18 01:04:49 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Sun Jan 18 01:04:49 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Sun Jan 18 01:04:49 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Sun Jan 18 01:04:49 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Sun Jan 18 01:04:49 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Sun Jan 18 01:04:49 2009] [notice] mod_python: using mutex_directory /tmp 
[Sun Jan 18 01:04:49 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Sun Jan 18 01:04:50 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Sun Jan 18 01:05:08 2009] [notice] caught SIGTERM, shutting down
[Sun Jan 18 01:05:11 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Sun Jan 18 01:05:11 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Sun Jan 18 01:05:11 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Sun Jan 18 01:05:11 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Sun Jan 18 01:05:11 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Sun Jan 18 01:05:11 2009] [notice] mod_python: using mutex_directory /tmp 
[Sun Jan 18 01:05:11 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Sun Jan 18 01:05:12 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Sun Jan 18 01:07:38 2009] [notice] caught SIGTERM, shutting down
[Sun Jan 18 01:07:41 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Sun Jan 18 01:07:41 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Sun Jan 18 01:07:41 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Sun Jan 18 01:07:41 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Sun Jan 18 01:07:41 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Sun Jan 18 01:07:41 2009] [notice] mod_python: using mutex_directory /tmp 
[Sun Jan 18 01:07:41 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Sun Jan 18 01:07:42 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Sun Jan 18 01:08:26 2009] [notice] caught SIGTERM, shutting down
[Sun Jan 18 01:08:29 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Sun Jan 18 01:08:29 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Sun Jan 18 01:08:29 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Sun Jan 18 01:08:29 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Sun Jan 18 01:08:29 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Sun Jan 18 01:08:29 2009] [notice] mod_python: using mutex_directory /tmp 
[Sun Jan 18 01:08:29 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Sun Jan 18 01:08:30 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Sun Jan 18 01:48:53 2009] [notice] caught SIGTERM, shutting down
[Sun Jan 18 01:48:56 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Sun Jan 18 01:48:56 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Sun Jan 18 01:48:56 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Sun Jan 18 01:48:56 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Sun Jan 18 01:48:56 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Sun Jan 18 01:48:56 2009] [notice] mod_python: using mutex_directory /tmp 
[Sun Jan 18 01:48:56 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Sun Jan 18 01:48:57 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Sun Jan 18 01:49:06 2009] [notice] caught SIGTERM, shutting down
[Sun Jan 18 01:49:09 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Sun Jan 18 01:49:09 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Sun Jan 18 01:49:09 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Sun Jan 18 01:49:09 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Sun Jan 18 01:49:09 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Sun Jan 18 01:49:09 2009] [notice] mod_python: using mutex_directory /tmp 
[Sun Jan 18 01:49:09 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Sun Jan 18 01:49:10 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Sun Jan 18 01:50:33 2009] [notice] caught SIGTERM, shutting down
[Sun Jan 18 01:50:36 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Sun Jan 18 01:50:36 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Sun Jan 18 01:50:36 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Sun Jan 18 01:50:36 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Sun Jan 18 01:50:36 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Sun Jan 18 01:50:36 2009] [notice] mod_python: using mutex_directory /tmp 
[Sun Jan 18 01:50:36 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Sun Jan 18 01:50:37 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Sun Jan 18 01:53:06 2009] [notice] caught SIGTERM, shutting down
[Sun Jan 18 01:53:09 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Sun Jan 18 01:53:09 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Sun Jan 18 01:53:09 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Sun Jan 18 01:53:09 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Sun Jan 18 01:53:09 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Sun Jan 18 01:53:09 2009] [notice] mod_python: using mutex_directory /tmp 
[Sun Jan 18 01:53:09 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Sun Jan 18 01:53:10 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Sun Jan 18 01:53:36 2009] [notice] caught SIGTERM, shutting down
[Sun Jan 18 01:53:39 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Sun Jan 18 01:53:39 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Sun Jan 18 01:53:39 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Sun Jan 18 01:53:39 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Sun Jan 18 01:53:39 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Sun Jan 18 01:53:39 2009] [notice] mod_python: using mutex_directory /tmp 
[Sun Jan 18 01:53:39 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Sun Jan 18 01:53:40 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Sun Jan 18 01:53:54 2009] [notice] caught SIGTERM, shutting down
[Sun Jan 18 01:53:57 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Sun Jan 18 01:53:57 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Sun Jan 18 01:53:57 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Sun Jan 18 01:53:57 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Sun Jan 18 01:53:57 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Sun Jan 18 01:53:57 2009] [notice] mod_python: using mutex_directory /tmp 
[Sun Jan 18 01:53:57 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Sun Jan 18 01:53:58 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Sun Jan 18 01:55:23 2009] [notice] caught SIGTERM, shutting down
[Sun Jan 18 01:55:26 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Sun Jan 18 01:55:26 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Sun Jan 18 01:55:26 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Sun Jan 18 01:55:26 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Sun Jan 18 01:55:26 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Sun Jan 18 01:55:26 2009] [notice] mod_python: using mutex_directory /tmp 
[Sun Jan 18 01:55:26 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Sun Jan 18 01:55:27 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Sun Jan 18 01:55:36 2009] [notice] caught SIGTERM, shutting down
[Sun Jan 18 01:55:39 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Sun Jan 18 01:55:39 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Sun Jan 18 01:55:39 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Sun Jan 18 01:55:39 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Sun Jan 18 01:55:39 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Sun Jan 18 01:55:39 2009] [notice] mod_python: using mutex_directory /tmp 
[Sun Jan 18 01:55:39 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Sun Jan 18 01:55:40 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Sun Jan 18 02:04:30 2009] [notice] caught SIGTERM, shutting down
[Sun Jan 18 02:04:33 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Sun Jan 18 02:04:33 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Sun Jan 18 02:04:33 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Sun Jan 18 02:04:33 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Sun Jan 18 02:04:33 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Sun Jan 18 02:04:33 2009] [notice] mod_python: using mutex_directory /tmp 
[Sun Jan 18 02:04:33 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Sun Jan 18 02:04:34 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Sun Jan 18 02:06:28 2009] [notice] caught SIGTERM, shutting down
[Sun Jan 18 02:06:31 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Sun Jan 18 02:06:31 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Sun Jan 18 02:06:31 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Sun Jan 18 02:06:31 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Sun Jan 18 02:06:31 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Sun Jan 18 02:06:31 2009] [notice] mod_python: using mutex_directory /tmp 
[Sun Jan 18 02:06:31 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Sun Jan 18 02:06:32 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Sun Jan 18 02:07:44 2009] [notice] caught SIGTERM, shutting down
[Sun Jan 18 02:07:47 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Sun Jan 18 02:07:47 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Sun Jan 18 02:07:47 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Sun Jan 18 02:07:47 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Sun Jan 18 02:07:47 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Sun Jan 18 02:07:47 2009] [notice] mod_python: using mutex_directory /tmp 
[Sun Jan 18 02:07:47 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Sun Jan 18 02:07:48 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Sun Jan 18 02:09:18 2009] [notice] caught SIGTERM, shutting down
[Sun Jan 18 02:09:21 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Sun Jan 18 02:09:21 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Sun Jan 18 02:09:21 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Sun Jan 18 02:09:21 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Sun Jan 18 02:09:21 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Sun Jan 18 02:09:21 2009] [notice] mod_python: using mutex_directory /tmp 
[Sun Jan 18 02:09:21 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Sun Jan 18 02:09:22 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Sun Jan 18 02:10:22 2009] [notice] caught SIGTERM, shutting down
[Sun Jan 18 02:10:25 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Sun Jan 18 02:10:25 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Sun Jan 18 02:10:25 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Sun Jan 18 02:10:25 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Sun Jan 18 02:10:25 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Sun Jan 18 02:10:25 2009] [notice] mod_python: using mutex_directory /tmp 
[Sun Jan 18 02:10:25 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Sun Jan 18 02:10:26 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Sun Jan 18 02:26:54 2009] [notice] caught SIGTERM, shutting down
[Sun Jan 18 02:26:57 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Sun Jan 18 02:26:57 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Sun Jan 18 02:26:57 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Sun Jan 18 02:26:57 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Sun Jan 18 02:26:57 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Sun Jan 18 02:26:57 2009] [notice] mod_python: using mutex_directory /tmp 
[Sun Jan 18 02:26:57 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Sun Jan 18 02:26:58 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Sun Jan 18 02:27:46 2009] [notice] caught SIGTERM, shutting down
[Sun Jan 18 02:27:49 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Sun Jan 18 02:27:49 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Sun Jan 18 02:27:49 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Sun Jan 18 02:27:49 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Sun Jan 18 02:27:49 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Sun Jan 18 02:27:49 2009] [notice] mod_python: using mutex_directory /tmp 
[Sun Jan 18 02:27:49 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Sun Jan 18 02:27:50 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Sun Jan 18 03:07:14 2009] [notice] caught SIGTERM, shutting down
[Sun Jan 18 03:07:17 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Sun Jan 18 03:07:17 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Sun Jan 18 03:07:17 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Sun Jan 18 03:07:17 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Sun Jan 18 03:07:17 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Sun Jan 18 03:07:17 2009] [notice] mod_python: using mutex_directory /tmp 
[Sun Jan 18 03:07:17 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Sun Jan 18 03:07:18 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Sun Jan 18 03:09:09 2009] [notice] caught SIGTERM, shutting down
[Sun Jan 18 03:09:12 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Sun Jan 18 03:09:12 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Sun Jan 18 03:09:12 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Sun Jan 18 03:09:12 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Sun Jan 18 03:09:12 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Sun Jan 18 03:09:12 2009] [notice] mod_python: using mutex_directory /tmp 
[Sun Jan 18 03:09:12 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Sun Jan 18 03:09:13 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Mon Jan 19 02:50:33 2009] [notice] caught SIGTERM, shutting down
[Mon Jan 19 02:50:36 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Mon Jan 19 02:50:36 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Mon Jan 19 02:50:36 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Mon Jan 19 02:50:36 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Mon Jan 19 02:50:36 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Mon Jan 19 02:50:36 2009] [notice] mod_python: using mutex_directory /tmp 
[Mon Jan 19 02:50:36 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Mon Jan 19 02:50:37 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Mon Jan 19 02:51:56 2009] [notice] caught SIGTERM, shutting down
[Mon Jan 19 02:51:59 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Mon Jan 19 02:51:59 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Mon Jan 19 02:51:59 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Mon Jan 19 02:51:59 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Mon Jan 19 02:51:59 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Mon Jan 19 02:51:59 2009] [notice] mod_python: using mutex_directory /tmp 
[Mon Jan 19 02:51:59 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Mon Jan 19 02:52:00 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Mon Jan 19 02:59:24 2009] [notice] caught SIGTERM, shutting down
[Mon Jan 19 02:59:27 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Mon Jan 19 02:59:27 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Mon Jan 19 02:59:27 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Mon Jan 19 02:59:27 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Mon Jan 19 02:59:27 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Mon Jan 19 02:59:27 2009] [notice] mod_python: using mutex_directory /tmp 
[Mon Jan 19 02:59:27 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Mon Jan 19 02:59:28 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Mon Jan 19 03:00:49 2009] [notice] caught SIGTERM, shutting down
[Mon Jan 19 03:00:52 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Mon Jan 19 03:00:52 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Mon Jan 19 03:00:52 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Mon Jan 19 03:00:52 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Mon Jan 19 03:00:52 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Mon Jan 19 03:00:52 2009] [notice] mod_python: using mutex_directory /tmp 
[Mon Jan 19 03:00:52 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Mon Jan 19 03:00:53 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Mon Jan 19 03:17:12 2009] [notice] caught SIGTERM, shutting down
[Mon Jan 19 03:17:15 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Mon Jan 19 03:17:15 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Mon Jan 19 03:17:15 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Mon Jan 19 03:17:15 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Mon Jan 19 03:17:15 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Mon Jan 19 03:17:15 2009] [notice] mod_python: using mutex_directory /tmp 
[Mon Jan 19 03:17:15 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Mon Jan 19 03:17:16 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Mon Jan 19 13:41:07 2009] [notice] caught SIGTERM, shutting down
[Mon Jan 19 13:41:10 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Mon Jan 19 13:41:10 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Mon Jan 19 13:41:10 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Mon Jan 19 13:41:10 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Mon Jan 19 13:41:10 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Mon Jan 19 13:41:10 2009] [notice] mod_python: using mutex_directory /tmp 
[Mon Jan 19 13:41:10 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Mon Jan 19 13:41:11 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Mon Jan 19 13:43:50 2009] [notice] caught SIGTERM, shutting down
[Mon Jan 19 13:43:53 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Mon Jan 19 13:43:53 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Mon Jan 19 13:43:53 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Mon Jan 19 13:43:53 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Mon Jan 19 13:43:53 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Mon Jan 19 13:43:53 2009] [notice] mod_python: using mutex_directory /tmp 
[Mon Jan 19 13:43:53 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Mon Jan 19 13:43:54 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Mon Jan 19 13:44:34 2009] [notice] caught SIGTERM, shutting down
[Mon Jan 19 13:44:37 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Mon Jan 19 13:44:37 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Mon Jan 19 13:44:37 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Mon Jan 19 13:44:37 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Mon Jan 19 13:44:37 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Mon Jan 19 13:44:37 2009] [notice] mod_python: using mutex_directory /tmp 
[Mon Jan 19 13:44:37 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Mon Jan 19 13:44:38 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Mon Jan 19 13:45:02 2009] [notice] caught SIGTERM, shutting down
[Mon Jan 19 13:45:05 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Mon Jan 19 13:45:05 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Mon Jan 19 13:45:05 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Mon Jan 19 13:45:05 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Mon Jan 19 13:45:05 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Mon Jan 19 13:45:05 2009] [notice] mod_python: using mutex_directory /tmp 
[Mon Jan 19 13:45:05 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Mon Jan 19 13:45:06 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Mon Jan 19 13:46:10 2009] [notice] caught SIGTERM, shutting down
[Mon Jan 19 13:46:13 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Mon Jan 19 13:46:13 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Mon Jan 19 13:46:13 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Mon Jan 19 13:46:13 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Mon Jan 19 13:46:13 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Mon Jan 19 13:46:13 2009] [notice] mod_python: using mutex_directory /tmp 
[Mon Jan 19 13:46:13 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Mon Jan 19 13:46:14 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Mon Jan 19 13:47:28 2009] [notice] caught SIGTERM, shutting down
[Mon Jan 19 13:47:31 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Mon Jan 19 13:47:31 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Mon Jan 19 13:47:31 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Mon Jan 19 13:47:31 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Mon Jan 19 13:47:31 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Mon Jan 19 13:47:31 2009] [notice] mod_python: using mutex_directory /tmp 
[Mon Jan 19 13:47:31 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Mon Jan 19 13:47:32 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Mon Jan 19 15:44:19 2009] [notice] caught SIGTERM, shutting down
[Mon Jan 19 15:44:22 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Mon Jan 19 15:44:22 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Mon Jan 19 15:44:22 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Mon Jan 19 15:44:22 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Mon Jan 19 15:44:22 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Mon Jan 19 15:44:22 2009] [notice] mod_python: using mutex_directory /tmp 
[Mon Jan 19 15:44:22 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Mon Jan 19 15:44:23 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Tue Jan 20 00:46:04 2009] [notice] caught SIGTERM, shutting down
[Tue Jan 20 00:46:07 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Tue Jan 20 00:46:07 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Tue Jan 20 00:46:07 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Tue Jan 20 00:46:07 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Tue Jan 20 00:46:07 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Tue Jan 20 00:46:07 2009] [notice] mod_python: using mutex_directory /tmp 
[Tue Jan 20 00:46:07 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Tue Jan 20 00:46:08 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Tue Jan 20 01:05:37 2009] [notice] caught SIGTERM, shutting down
[Tue Jan 20 01:05:40 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Tue Jan 20 01:05:40 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Tue Jan 20 01:05:40 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Tue Jan 20 01:05:40 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Tue Jan 20 01:05:40 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Tue Jan 20 01:05:40 2009] [notice] mod_python: using mutex_directory /tmp 
[Tue Jan 20 01:05:40 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Tue Jan 20 01:05:41 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Tue Jan 20 01:19:50 2009] [notice] caught SIGTERM, shutting down
[Tue Jan 20 01:19:53 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Tue Jan 20 01:19:53 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Tue Jan 20 01:19:53 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Tue Jan 20 01:19:53 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Tue Jan 20 01:19:53 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Tue Jan 20 01:19:53 2009] [notice] mod_python: using mutex_directory /tmp 
[Tue Jan 20 01:19:53 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Tue Jan 20 01:19:54 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Tue Jan 20 01:20:49 2009] [notice] caught SIGTERM, shutting down
[Tue Jan 20 01:20:52 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Tue Jan 20 01:20:52 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Tue Jan 20 01:20:52 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Tue Jan 20 01:20:52 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Tue Jan 20 01:20:52 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Tue Jan 20 01:20:52 2009] [notice] mod_python: using mutex_directory /tmp 
[Tue Jan 20 01:20:52 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Tue Jan 20 01:20:53 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Tue Jan 20 01:21:42 2009] [notice] caught SIGTERM, shutting down
[Tue Jan 20 01:21:45 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Tue Jan 20 01:21:45 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Tue Jan 20 01:21:45 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Tue Jan 20 01:21:45 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Tue Jan 20 01:21:45 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Tue Jan 20 01:21:45 2009] [notice] mod_python: using mutex_directory /tmp 
[Tue Jan 20 01:21:45 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Tue Jan 20 01:21:46 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Tue Jan 20 01:34:23 2009] [notice] caught SIGTERM, shutting down
[Tue Jan 20 01:34:26 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Tue Jan 20 01:34:26 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Tue Jan 20 01:34:26 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Tue Jan 20 01:34:26 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Tue Jan 20 01:34:26 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Tue Jan 20 01:34:26 2009] [notice] mod_python: using mutex_directory /tmp 
[Tue Jan 20 01:34:27 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Tue Jan 20 01:34:28 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Tue Jan 20 01:34:45 2009] [notice] caught SIGTERM, shutting down
[Tue Jan 20 01:34:48 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Tue Jan 20 01:34:48 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Tue Jan 20 01:34:48 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Tue Jan 20 01:34:48 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Tue Jan 20 01:34:48 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Tue Jan 20 01:34:48 2009] [notice] mod_python: using mutex_directory /tmp 
[Tue Jan 20 01:34:48 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Tue Jan 20 01:34:49 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Tue Jan 20 15:03:40 2009] [notice] caught SIGTERM, shutting down
[Tue Jan 20 15:03:43 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Tue Jan 20 15:03:43 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Tue Jan 20 15:03:43 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Tue Jan 20 15:03:43 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Tue Jan 20 15:03:43 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Tue Jan 20 15:03:43 2009] [notice] mod_python: using mutex_directory /tmp 
[Tue Jan 20 15:03:43 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Tue Jan 20 15:03:44 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Tue Jan 20 15:08:50 2009] [notice] caught SIGTERM, shutting down
[Tue Jan 20 15:08:53 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Tue Jan 20 15:08:53 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Tue Jan 20 15:08:53 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Tue Jan 20 15:08:53 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Tue Jan 20 15:08:53 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Tue Jan 20 15:08:53 2009] [notice] mod_python: using mutex_directory /tmp 
[Tue Jan 20 15:08:53 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Tue Jan 20 15:08:54 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Tue Jan 20 15:19:25 2009] [notice] caught SIGTERM, shutting down
[Tue Jan 20 15:19:28 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Tue Jan 20 15:19:28 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Tue Jan 20 15:19:28 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Tue Jan 20 15:19:28 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Tue Jan 20 15:19:28 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Tue Jan 20 15:19:28 2009] [notice] mod_python: using mutex_directory /tmp 
[Tue Jan 20 15:19:28 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Tue Jan 20 15:19:29 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Tue Jan 20 17:01:04 2009] [notice] caught SIGTERM, shutting down
[Tue Jan 20 17:01:07 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Tue Jan 20 17:01:07 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Tue Jan 20 17:01:07 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Tue Jan 20 17:01:07 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Tue Jan 20 17:01:07 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Tue Jan 20 17:01:07 2009] [notice] mod_python: using mutex_directory /tmp 
[Tue Jan 20 17:01:07 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Tue Jan 20 17:01:08 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Tue Jan 20 17:02:59 2009] [notice] caught SIGTERM, shutting down
[Tue Jan 20 17:03:02 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Tue Jan 20 17:03:02 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Tue Jan 20 17:03:02 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Tue Jan 20 17:03:02 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Tue Jan 20 17:03:02 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Tue Jan 20 17:03:02 2009] [notice] mod_python: using mutex_directory /tmp 
[Tue Jan 20 17:03:02 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Tue Jan 20 17:03:03 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Tue Jan 20 17:04:56 2009] [notice] caught SIGTERM, shutting down
[Tue Jan 20 17:04:59 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Tue Jan 20 17:04:59 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Tue Jan 20 17:04:59 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Tue Jan 20 17:04:59 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Tue Jan 20 17:04:59 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Tue Jan 20 17:04:59 2009] [notice] mod_python: using mutex_directory /tmp 
[Tue Jan 20 17:04:59 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Tue Jan 20 17:05:00 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Tue Jan 20 17:51:04 2009] [notice] caught SIGTERM, shutting down
[Tue Jan 20 17:51:07 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Tue Jan 20 17:51:07 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Tue Jan 20 17:51:07 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Tue Jan 20 17:51:07 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Tue Jan 20 17:51:07 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Tue Jan 20 17:51:07 2009] [notice] mod_python: using mutex_directory /tmp 
[Tue Jan 20 17:51:07 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Tue Jan 20 17:51:08 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Tue Jan 20 19:02:26 2009] [notice] caught SIGTERM, shutting down
[Tue Jan 20 19:02:29 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Tue Jan 20 19:02:29 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Tue Jan 20 19:02:29 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Tue Jan 20 19:02:29 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Tue Jan 20 19:02:29 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Tue Jan 20 19:02:29 2009] [notice] mod_python: using mutex_directory /tmp 
[Tue Jan 20 19:02:29 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Tue Jan 20 19:02:30 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Tue Jan 20 19:03:51 2009] [notice] caught SIGTERM, shutting down
[Tue Jan 20 19:03:54 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Tue Jan 20 19:03:54 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Tue Jan 20 19:03:54 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Tue Jan 20 19:03:54 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Tue Jan 20 19:03:54 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Tue Jan 20 19:03:54 2009] [notice] mod_python: using mutex_directory /tmp 
[Tue Jan 20 19:03:54 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Tue Jan 20 19:03:55 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Tue Jan 20 19:04:45 2009] [notice] caught SIGTERM, shutting down
[Tue Jan 20 19:04:48 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Tue Jan 20 19:04:48 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Tue Jan 20 19:04:48 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Tue Jan 20 19:04:48 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Tue Jan 20 19:04:48 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Tue Jan 20 19:04:48 2009] [notice] mod_python: using mutex_directory /tmp 
[Tue Jan 20 19:04:48 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Tue Jan 20 19:04:49 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Tue Jan 20 19:06:07 2009] [notice] caught SIGTERM, shutting down
[Tue Jan 20 19:06:10 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Tue Jan 20 19:06:10 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Tue Jan 20 19:06:10 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Tue Jan 20 19:06:10 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Tue Jan 20 19:06:10 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Tue Jan 20 19:06:10 2009] [notice] mod_python: using mutex_directory /tmp 
[Tue Jan 20 19:06:10 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Tue Jan 20 19:06:11 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Tue Jan 20 19:07:17 2009] [notice] caught SIGTERM, shutting down
[Tue Jan 20 19:07:20 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Tue Jan 20 19:07:20 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Tue Jan 20 19:07:20 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Tue Jan 20 19:07:20 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Tue Jan 20 19:07:20 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Tue Jan 20 19:07:20 2009] [notice] mod_python: using mutex_directory /tmp 
[Tue Jan 20 19:07:20 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Tue Jan 20 19:07:21 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Tue Jan 20 19:08:01 2009] [notice] caught SIGTERM, shutting down
[Tue Jan 20 19:08:04 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Tue Jan 20 19:08:04 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Tue Jan 20 19:08:04 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Tue Jan 20 19:08:04 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Tue Jan 20 19:08:04 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Tue Jan 20 19:08:04 2009] [notice] mod_python: using mutex_directory /tmp 
[Tue Jan 20 19:08:04 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Tue Jan 20 19:08:05 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Tue Jan 20 19:12:23 2009] [notice] caught SIGTERM, shutting down
[Tue Jan 20 19:12:26 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Tue Jan 20 19:12:26 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Tue Jan 20 19:12:26 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Tue Jan 20 19:12:26 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Tue Jan 20 19:12:26 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Tue Jan 20 19:12:26 2009] [notice] mod_python: using mutex_directory /tmp 
[Tue Jan 20 19:12:26 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Tue Jan 20 19:12:27 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Tue Jan 20 19:13:19 2009] [notice] caught SIGTERM, shutting down
[Tue Jan 20 19:13:22 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Tue Jan 20 19:13:22 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Tue Jan 20 19:13:22 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Tue Jan 20 19:13:22 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Tue Jan 20 19:13:22 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Tue Jan 20 19:13:22 2009] [notice] mod_python: using mutex_directory /tmp 
[Tue Jan 20 19:13:22 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Tue Jan 20 19:13:23 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Tue Jan 20 19:15:02 2009] [notice] caught SIGTERM, shutting down
[Tue Jan 20 19:15:05 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Tue Jan 20 19:15:05 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Tue Jan 20 19:15:05 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Tue Jan 20 19:15:05 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Tue Jan 20 19:15:05 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Tue Jan 20 19:15:05 2009] [notice] mod_python: using mutex_directory /tmp 
[Tue Jan 20 19:15:05 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Tue Jan 20 19:15:06 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Wed Jan 21 00:07:40 2009] [notice] caught SIGTERM, shutting down
[Wed Jan 21 00:07:43 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Wed Jan 21 00:07:43 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Wed Jan 21 00:07:43 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Wed Jan 21 00:07:43 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Wed Jan 21 00:07:43 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Wed Jan 21 00:07:43 2009] [notice] mod_python: using mutex_directory /tmp 
[Wed Jan 21 00:07:43 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Wed Jan 21 00:07:44 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Wed Jan 21 00:42:10 2009] [notice] caught SIGTERM, shutting down
[Wed Jan 21 00:42:13 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Wed Jan 21 00:42:13 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Wed Jan 21 00:42:13 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Wed Jan 21 00:42:13 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Wed Jan 21 00:42:13 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Wed Jan 21 00:42:13 2009] [notice] mod_python: using mutex_directory /tmp 
[Wed Jan 21 00:42:13 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Wed Jan 21 00:42:14 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Wed Jan 21 00:47:41 2009] [notice] caught SIGTERM, shutting down
[Wed Jan 21 00:47:44 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Wed Jan 21 00:47:44 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Wed Jan 21 00:47:44 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Wed Jan 21 00:47:44 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Wed Jan 21 00:47:44 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Wed Jan 21 00:47:44 2009] [notice] mod_python: using mutex_directory /tmp 
[Wed Jan 21 00:47:44 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Wed Jan 21 00:47:45 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Wed Jan 21 00:52:03 2009] [notice] caught SIGTERM, shutting down
[Wed Jan 21 00:52:06 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Wed Jan 21 00:52:06 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Wed Jan 21 00:52:06 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Wed Jan 21 00:52:06 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Wed Jan 21 00:52:06 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Wed Jan 21 00:52:06 2009] [notice] mod_python: using mutex_directory /tmp 
[Wed Jan 21 00:52:06 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Wed Jan 21 00:52:07 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Wed Jan 21 01:32:13 2009] [notice] caught SIGTERM, shutting down
[Wed Jan 21 01:32:16 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Wed Jan 21 01:32:16 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Wed Jan 21 01:32:16 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Wed Jan 21 01:32:16 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Wed Jan 21 01:32:16 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Wed Jan 21 01:32:16 2009] [notice] mod_python: using mutex_directory /tmp 
[Wed Jan 21 01:32:16 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Wed Jan 21 01:32:17 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Wed Jan 21 01:33:05 2009] [notice] caught SIGTERM, shutting down
[Wed Jan 21 01:33:08 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Wed Jan 21 01:33:08 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Wed Jan 21 01:33:08 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Wed Jan 21 01:33:08 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Wed Jan 21 01:33:08 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Wed Jan 21 01:33:08 2009] [notice] mod_python: using mutex_directory /tmp 
[Wed Jan 21 01:33:08 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Wed Jan 21 01:33:09 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Sun Jan 25 02:14:59 2009] [notice] caught SIGTERM, shutting down
[Sun Jan 25 02:15:02 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Sun Jan 25 02:15:02 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Sun Jan 25 02:15:02 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Sun Jan 25 02:15:02 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Sun Jan 25 02:15:02 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Sun Jan 25 02:15:02 2009] [notice] mod_python: using mutex_directory /tmp 
[Sun Jan 25 02:15:02 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Sun Jan 25 02:15:03 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Sun Jan 25 02:19:47 2009] [notice] caught SIGTERM, shutting down
[Sun Jan 25 02:19:50 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Sun Jan 25 02:19:50 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Sun Jan 25 02:19:50 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Sun Jan 25 02:19:50 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Sun Jan 25 02:19:50 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Sun Jan 25 02:19:50 2009] [notice] mod_python: using mutex_directory /tmp 
[Sun Jan 25 02:19:50 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Sun Jan 25 02:19:51 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Sun Jan 25 02:22:38 2009] [notice] caught SIGTERM, shutting down
[Sun Jan 25 02:22:41 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Sun Jan 25 02:22:41 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Sun Jan 25 02:22:41 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Sun Jan 25 02:22:41 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Sun Jan 25 02:22:41 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Sun Jan 25 02:22:41 2009] [notice] mod_python: using mutex_directory /tmp 
[Sun Jan 25 02:22:41 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Sun Jan 25 02:22:42 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Sun Jan 25 02:26:41 2009] [notice] caught SIGTERM, shutting down
[Sun Jan 25 02:26:44 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Sun Jan 25 02:26:44 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Sun Jan 25 02:26:44 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Sun Jan 25 02:26:44 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Sun Jan 25 02:26:44 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Sun Jan 25 02:26:44 2009] [notice] mod_python: using mutex_directory /tmp 
[Sun Jan 25 02:26:44 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Sun Jan 25 02:26:45 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Sun Jan 25 02:27:27 2009] [notice] caught SIGTERM, shutting down
[Sun Jan 25 02:27:30 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Sun Jan 25 02:27:30 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Sun Jan 25 02:27:30 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Sun Jan 25 02:27:30 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Sun Jan 25 02:27:30 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Sun Jan 25 02:27:30 2009] [notice] mod_python: using mutex_directory /tmp 
[Sun Jan 25 02:27:30 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Sun Jan 25 02:27:31 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Sun Jan 25 02:27:52 2009] [notice] caught SIGTERM, shutting down
[Sun Jan 25 02:27:56 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Sun Jan 25 02:27:56 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Sun Jan 25 02:27:56 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Sun Jan 25 02:27:56 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Sun Jan 25 02:27:56 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Sun Jan 25 02:27:56 2009] [notice] mod_python: using mutex_directory /tmp 
[Sun Jan 25 02:27:56 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Sun Jan 25 02:27:57 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Tue Jan 27 19:18:47 2009] [notice] caught SIGTERM, shutting down
[Tue Jan 27 19:18:50 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Tue Jan 27 19:18:50 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Tue Jan 27 19:18:50 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Tue Jan 27 19:18:50 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Tue Jan 27 19:18:50 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Tue Jan 27 19:18:50 2009] [notice] mod_python: using mutex_directory /tmp 
[Tue Jan 27 19:18:50 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Tue Jan 27 19:18:51 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Tue Jan 27 19:19:54 2009] [notice] caught SIGTERM, shutting down
[Tue Jan 27 19:19:57 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Tue Jan 27 19:19:57 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Tue Jan 27 19:19:57 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Tue Jan 27 19:19:57 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Tue Jan 27 19:19:57 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Tue Jan 27 19:19:57 2009] [notice] mod_python: using mutex_directory /tmp 
[Tue Jan 27 19:19:57 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Tue Jan 27 19:19:58 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Tue Jan 27 19:21:35 2009] [notice] caught SIGTERM, shutting down
[Tue Jan 27 19:21:38 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Tue Jan 27 19:21:38 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Tue Jan 27 19:21:38 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Tue Jan 27 19:21:38 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Tue Jan 27 19:21:38 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Tue Jan 27 19:21:38 2009] [notice] mod_python: using mutex_directory /tmp 
[Tue Jan 27 19:21:38 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Tue Jan 27 19:21:39 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Fri Jan 30 00:08:13 2009] [notice] caught SIGTERM, shutting down
[Fri Jan 30 00:08:16 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Fri Jan 30 00:08:16 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Fri Jan 30 00:08:16 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Fri Jan 30 00:08:16 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Fri Jan 30 00:08:16 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Fri Jan 30 00:08:16 2009] [notice] mod_python: using mutex_directory /tmp 
[Fri Jan 30 00:08:16 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Fri Jan 30 00:08:17 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Fri Jan 30 06:08:19 2009] [error] [client 127.0.0.1] mod_python (pid=6084, interpreter='web63.webfaction.com', phase='PythonHandler', handler='django.core.handlers.modpython'): Application error
[Fri Jan 30 06:08:19 2009] [error] [client 127.0.0.1] ServerName: 'web63.webfaction.com'
[Fri Jan 30 06:08:19 2009] [error] [client 127.0.0.1] DocumentRoot: '/etc/httpd/htdocs'
[Fri Jan 30 06:08:19 2009] [error] [client 127.0.0.1] URI: '/first-page/'
[Fri Jan 30 06:08:19 2009] [error] [client 127.0.0.1] Location: '/'
[Fri Jan 30 06:08:19 2009] [error] [client 127.0.0.1] Directory: None
[Fri Jan 30 06:08:19 2009] [error] [client 127.0.0.1] Filename: '/etc/httpd/htdocs'
[Fri Jan 30 06:08:19 2009] [error] [client 127.0.0.1] PathInfo: '/first-page/'
[Fri Jan 30 06:08:19 2009] [error] [client 127.0.0.1] Traceback (most recent call last):
[Fri Jan 30 06:08:19 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1537, in HandlerDispatch\n    default=default_handler, arg=req, silent=hlist.silent)
[Fri Jan 30 06:08:19 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1229, in _process_target\n    result = _execute_target(config, req, object, arg)
[Fri Jan 30 06:08:19 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1128, in _execute_target\n    result = object(arg)
[Fri Jan 30 06:08:19 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/modpython.py", line 228, in handler\n    return ModPythonHandler()(req)
[Fri Jan 30 06:08:19 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/modpython.py", line 191, in __call__\n    self.load_middleware()
[Fri Jan 30 06:08:19 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/base.py", line 44, in load_middleware\n    raise exceptions.ImproperlyConfigured, 'Middleware module "%s" does not define a "%s" class' % (mw_module, mw_classname)
[Fri Jan 30 06:08:19 2009] [error] [client 127.0.0.1] ImproperlyConfigured: Middleware module "django.contrib.flatpages.middleware" does not define a "FlatPageFallbackMiddleware" class
[Fri Jan 30 06:08:24 2009] [error] [client 127.0.0.1] mod_python (pid=6085, interpreter='web63.webfaction.com', phase='PythonHandler', handler='django.core.handlers.modpython'): Application error
[Fri Jan 30 06:08:24 2009] [error] [client 127.0.0.1] ServerName: 'web63.webfaction.com'
[Fri Jan 30 06:08:24 2009] [error] [client 127.0.0.1] DocumentRoot: '/etc/httpd/htdocs'
[Fri Jan 30 06:08:24 2009] [error] [client 127.0.0.1] URI: '/first-page/'
[Fri Jan 30 06:08:24 2009] [error] [client 127.0.0.1] Location: '/'
[Fri Jan 30 06:08:24 2009] [error] [client 127.0.0.1] Directory: None
[Fri Jan 30 06:08:24 2009] [error] [client 127.0.0.1] Filename: '/etc/httpd/htdocs'
[Fri Jan 30 06:08:24 2009] [error] [client 127.0.0.1] PathInfo: '/first-page/'
[Fri Jan 30 06:08:24 2009] [error] [client 127.0.0.1] Traceback (most recent call last):
[Fri Jan 30 06:08:24 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1537, in HandlerDispatch\n    default=default_handler, arg=req, silent=hlist.silent)
[Fri Jan 30 06:08:24 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1229, in _process_target\n    result = _execute_target(config, req, object, arg)
[Fri Jan 30 06:08:24 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1128, in _execute_target\n    result = object(arg)
[Fri Jan 30 06:08:24 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/modpython.py", line 228, in handler\n    return ModPythonHandler()(req)
[Fri Jan 30 06:08:24 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/modpython.py", line 191, in __call__\n    self.load_middleware()
[Fri Jan 30 06:08:24 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/base.py", line 44, in load_middleware\n    raise exceptions.ImproperlyConfigured, 'Middleware module "%s" does not define a "%s" class' % (mw_module, mw_classname)
[Fri Jan 30 06:08:24 2009] [error] [client 127.0.0.1] ImproperlyConfigured: Middleware module "django.contrib.flatpages.middleware" does not define a "FlatPageFallbackMiddleware" class
[Fri Jan 30 06:08:34 2009] [error] [client 127.0.0.1] mod_python (pid=6084, interpreter='web63.webfaction.com', phase='PythonHandler', handler='django.core.handlers.modpython'): Application error
[Fri Jan 30 06:08:34 2009] [error] [client 127.0.0.1] ServerName: 'web63.webfaction.com'
[Fri Jan 30 06:08:34 2009] [error] [client 127.0.0.1] DocumentRoot: '/etc/httpd/htdocs'
[Fri Jan 30 06:08:34 2009] [error] [client 127.0.0.1] URI: '/'
[Fri Jan 30 06:08:34 2009] [error] [client 127.0.0.1] Location: '/'
[Fri Jan 30 06:08:34 2009] [error] [client 127.0.0.1] Directory: None
[Fri Jan 30 06:08:34 2009] [error] [client 127.0.0.1] Filename: '/etc/httpd/htdocs'
[Fri Jan 30 06:08:34 2009] [error] [client 127.0.0.1] PathInfo: '/'
[Fri Jan 30 06:08:34 2009] [error] [client 127.0.0.1] Traceback (most recent call last):
[Fri Jan 30 06:08:34 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1537, in HandlerDispatch\n    default=default_handler, arg=req, silent=hlist.silent)
[Fri Jan 30 06:08:34 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1229, in _process_target\n    result = _execute_target(config, req, object, arg)
[Fri Jan 30 06:08:34 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1128, in _execute_target\n    result = object(arg)
[Fri Jan 30 06:08:34 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/modpython.py", line 228, in handler\n    return ModPythonHandler()(req)
[Fri Jan 30 06:08:34 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/modpython.py", line 191, in __call__\n    self.load_middleware()
[Fri Jan 30 06:08:34 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/base.py", line 44, in load_middleware\n    raise exceptions.ImproperlyConfigured, 'Middleware module "%s" does not define a "%s" class' % (mw_module, mw_classname)
[Fri Jan 30 06:08:34 2009] [error] [client 127.0.0.1] ImproperlyConfigured: Middleware module "django.contrib.flatpages.middleware" does not define a "FlatPageFallbackMiddleware" class
[Fri Jan 30 06:08:36 2009] [error] [client 127.0.0.1] mod_python (pid=6085, interpreter='web63.webfaction.com', phase='PythonHandler', handler='django.core.handlers.modpython'): Application error
[Fri Jan 30 06:08:36 2009] [error] [client 127.0.0.1] ServerName: 'web63.webfaction.com'
[Fri Jan 30 06:08:36 2009] [error] [client 127.0.0.1] DocumentRoot: '/etc/httpd/htdocs'
[Fri Jan 30 06:08:36 2009] [error] [client 127.0.0.1] URI: '/'
[Fri Jan 30 06:08:36 2009] [error] [client 127.0.0.1] Location: '/'
[Fri Jan 30 06:08:36 2009] [error] [client 127.0.0.1] Directory: None
[Fri Jan 30 06:08:36 2009] [error] [client 127.0.0.1] Filename: '/etc/httpd/htdocs'
[Fri Jan 30 06:08:36 2009] [error] [client 127.0.0.1] PathInfo: '/'
[Fri Jan 30 06:08:36 2009] [error] [client 127.0.0.1] Traceback (most recent call last):
[Fri Jan 30 06:08:36 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1537, in HandlerDispatch\n    default=default_handler, arg=req, silent=hlist.silent)
[Fri Jan 30 06:08:36 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1229, in _process_target\n    result = _execute_target(config, req, object, arg)
[Fri Jan 30 06:08:36 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1128, in _execute_target\n    result = object(arg)
[Fri Jan 30 06:08:36 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/modpython.py", line 228, in handler\n    return ModPythonHandler()(req)
[Fri Jan 30 06:08:36 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/modpython.py", line 191, in __call__\n    self.load_middleware()
[Fri Jan 30 06:08:36 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/base.py", line 44, in load_middleware\n    raise exceptions.ImproperlyConfigured, 'Middleware module "%s" does not define a "%s" class' % (mw_module, mw_classname)
[Fri Jan 30 06:08:36 2009] [error] [client 127.0.0.1] ImproperlyConfigured: Middleware module "django.contrib.flatpages.middleware" does not define a "FlatPageFallbackMiddleware" class
[Fri Jan 30 06:08:38 2009] [error] [client 127.0.0.1] mod_python (pid=6084, interpreter='web63.webfaction.com', phase='PythonHandler', handler='django.core.handlers.modpython'): Application error
[Fri Jan 30 06:08:38 2009] [error] [client 127.0.0.1] ServerName: 'web63.webfaction.com'
[Fri Jan 30 06:08:38 2009] [error] [client 127.0.0.1] DocumentRoot: '/etc/httpd/htdocs'
[Fri Jan 30 06:08:38 2009] [error] [client 127.0.0.1] URI: '/'
[Fri Jan 30 06:08:38 2009] [error] [client 127.0.0.1] Location: '/'
[Fri Jan 30 06:08:38 2009] [error] [client 127.0.0.1] Directory: None
[Fri Jan 30 06:08:38 2009] [error] [client 127.0.0.1] Filename: '/etc/httpd/htdocs'
[Fri Jan 30 06:08:38 2009] [error] [client 127.0.0.1] PathInfo: '/'
[Fri Jan 30 06:08:38 2009] [error] [client 127.0.0.1] Traceback (most recent call last):
[Fri Jan 30 06:08:38 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1537, in HandlerDispatch\n    default=default_handler, arg=req, silent=hlist.silent)
[Fri Jan 30 06:08:38 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1229, in _process_target\n    result = _execute_target(config, req, object, arg)
[Fri Jan 30 06:08:38 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1128, in _execute_target\n    result = object(arg)
[Fri Jan 30 06:08:38 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/modpython.py", line 228, in handler\n    return ModPythonHandler()(req)
[Fri Jan 30 06:08:38 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/modpython.py", line 191, in __call__\n    self.load_middleware()
[Fri Jan 30 06:08:38 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/base.py", line 44, in load_middleware\n    raise exceptions.ImproperlyConfigured, 'Middleware module "%s" does not define a "%s" class' % (mw_module, mw_classname)
[Fri Jan 30 06:08:38 2009] [error] [client 127.0.0.1] ImproperlyConfigured: Middleware module "django.contrib.flatpages.middleware" does not define a "FlatPageFallbackMiddleware" class
[Fri Jan 30 00:09:36 2009] [notice] caught SIGTERM, shutting down
[Fri Jan 30 00:09:39 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Fri Jan 30 00:09:39 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Fri Jan 30 00:09:39 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Fri Jan 30 00:09:39 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Fri Jan 30 00:09:39 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Fri Jan 30 00:09:39 2009] [notice] mod_python: using mutex_directory /tmp 
[Fri Jan 30 00:09:39 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Fri Jan 30 00:09:40 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Fri Jan 30 06:09:41 2009] [error] [client 127.0.0.1] mod_python (pid=6306, interpreter='web63.webfaction.com', phase='PythonHandler', handler='django.core.handlers.modpython'): Application error
[Fri Jan 30 06:09:41 2009] [error] [client 127.0.0.1] ServerName: 'web63.webfaction.com'
[Fri Jan 30 06:09:41 2009] [error] [client 127.0.0.1] DocumentRoot: '/etc/httpd/htdocs'
[Fri Jan 30 06:09:41 2009] [error] [client 127.0.0.1] URI: '/'
[Fri Jan 30 06:09:41 2009] [error] [client 127.0.0.1] Location: '/'
[Fri Jan 30 06:09:41 2009] [error] [client 127.0.0.1] Directory: None
[Fri Jan 30 06:09:41 2009] [error] [client 127.0.0.1] Filename: '/etc/httpd/htdocs'
[Fri Jan 30 06:09:41 2009] [error] [client 127.0.0.1] PathInfo: '/'
[Fri Jan 30 06:09:41 2009] [error] [client 127.0.0.1] Traceback (most recent call last):
[Fri Jan 30 06:09:41 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1537, in HandlerDispatch\n    default=default_handler, arg=req, silent=hlist.silent)
[Fri Jan 30 06:09:41 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1229, in _process_target\n    result = _execute_target(config, req, object, arg)
[Fri Jan 30 06:09:41 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1128, in _execute_target\n    result = object(arg)
[Fri Jan 30 06:09:41 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/modpython.py", line 228, in handler\n    return ModPythonHandler()(req)
[Fri Jan 30 06:09:41 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/modpython.py", line 191, in __call__\n    self.load_middleware()
[Fri Jan 30 06:09:41 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/base.py", line 44, in load_middleware\n    raise exceptions.ImproperlyConfigured, 'Middleware module "%s" does not define a "%s" class' % (mw_module, mw_classname)
[Fri Jan 30 06:09:41 2009] [error] [client 127.0.0.1] ImproperlyConfigured: Middleware module "django.contrib.flatpages.middleware" does not define a "FlatPageFallbackMiddleware" class
[Fri Jan 30 06:09:44 2009] [error] [client 127.0.0.1] mod_python (pid=6307, interpreter='web63.webfaction.com', phase='PythonHandler', handler='django.core.handlers.modpython'): Application error
[Fri Jan 30 06:09:44 2009] [error] [client 127.0.0.1] ServerName: 'web63.webfaction.com'
[Fri Jan 30 06:09:44 2009] [error] [client 127.0.0.1] DocumentRoot: '/etc/httpd/htdocs'
[Fri Jan 30 06:09:44 2009] [error] [client 127.0.0.1] URI: '/'
[Fri Jan 30 06:09:44 2009] [error] [client 127.0.0.1] Location: '/'
[Fri Jan 30 06:09:44 2009] [error] [client 127.0.0.1] Directory: None
[Fri Jan 30 06:09:44 2009] [error] [client 127.0.0.1] Filename: '/etc/httpd/htdocs'
[Fri Jan 30 06:09:44 2009] [error] [client 127.0.0.1] PathInfo: '/'
[Fri Jan 30 06:09:44 2009] [error] [client 127.0.0.1] Traceback (most recent call last):
[Fri Jan 30 06:09:44 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1537, in HandlerDispatch\n    default=default_handler, arg=req, silent=hlist.silent)
[Fri Jan 30 06:09:44 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1229, in _process_target\n    result = _execute_target(config, req, object, arg)
[Fri Jan 30 06:09:44 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1128, in _execute_target\n    result = object(arg)
[Fri Jan 30 06:09:44 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/modpython.py", line 228, in handler\n    return ModPythonHandler()(req)
[Fri Jan 30 06:09:44 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/modpython.py", line 191, in __call__\n    self.load_middleware()
[Fri Jan 30 06:09:44 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/base.py", line 44, in load_middleware\n    raise exceptions.ImproperlyConfigured, 'Middleware module "%s" does not define a "%s" class' % (mw_module, mw_classname)
[Fri Jan 30 06:09:44 2009] [error] [client 127.0.0.1] ImproperlyConfigured: Middleware module "django.contrib.flatpages.middleware" does not define a "FlatPageFallbackMiddleware" class
[Fri Jan 30 06:09:45 2009] [error] [client 127.0.0.1] mod_python (pid=6306, interpreter='web63.webfaction.com', phase='PythonHandler', handler='django.core.handlers.modpython'): Application error
[Fri Jan 30 06:09:45 2009] [error] [client 127.0.0.1] ServerName: 'web63.webfaction.com'
[Fri Jan 30 06:09:45 2009] [error] [client 127.0.0.1] DocumentRoot: '/etc/httpd/htdocs'
[Fri Jan 30 06:09:45 2009] [error] [client 127.0.0.1] URI: '/'
[Fri Jan 30 06:09:45 2009] [error] [client 127.0.0.1] Location: '/'
[Fri Jan 30 06:09:45 2009] [error] [client 127.0.0.1] Directory: None
[Fri Jan 30 06:09:45 2009] [error] [client 127.0.0.1] Filename: '/etc/httpd/htdocs'
[Fri Jan 30 06:09:45 2009] [error] [client 127.0.0.1] PathInfo: '/'
[Fri Jan 30 06:09:45 2009] [error] [client 127.0.0.1] Traceback (most recent call last):
[Fri Jan 30 06:09:45 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1537, in HandlerDispatch\n    default=default_handler, arg=req, silent=hlist.silent)
[Fri Jan 30 06:09:45 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1229, in _process_target\n    result = _execute_target(config, req, object, arg)
[Fri Jan 30 06:09:45 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1128, in _execute_target\n    result = object(arg)
[Fri Jan 30 06:09:45 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/modpython.py", line 228, in handler\n    return ModPythonHandler()(req)
[Fri Jan 30 06:09:45 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/modpython.py", line 191, in __call__\n    self.load_middleware()
[Fri Jan 30 06:09:45 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/base.py", line 44, in load_middleware\n    raise exceptions.ImproperlyConfigured, 'Middleware module "%s" does not define a "%s" class' % (mw_module, mw_classname)
[Fri Jan 30 06:09:45 2009] [error] [client 127.0.0.1] ImproperlyConfigured: Middleware module "django.contrib.flatpages.middleware" does not define a "FlatPageFallbackMiddleware" class
[Fri Jan 30 06:09:48 2009] [error] [client 127.0.0.1] mod_python (pid=6307, interpreter='web63.webfaction.com', phase='PythonHandler', handler='django.core.handlers.modpython'): Application error
[Fri Jan 30 06:09:48 2009] [error] [client 127.0.0.1] ServerName: 'web63.webfaction.com'
[Fri Jan 30 06:09:48 2009] [error] [client 127.0.0.1] DocumentRoot: '/etc/httpd/htdocs'
[Fri Jan 30 06:09:48 2009] [error] [client 127.0.0.1] URI: '/admin/'
[Fri Jan 30 06:09:48 2009] [error] [client 127.0.0.1] Location: '/'
[Fri Jan 30 06:09:48 2009] [error] [client 127.0.0.1] Directory: None
[Fri Jan 30 06:09:48 2009] [error] [client 127.0.0.1] Filename: '/etc/httpd/htdocs'
[Fri Jan 30 06:09:48 2009] [error] [client 127.0.0.1] PathInfo: '/admin/'
[Fri Jan 30 06:09:48 2009] [error] [client 127.0.0.1] Traceback (most recent call last):
[Fri Jan 30 06:09:48 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1537, in HandlerDispatch\n    default=default_handler, arg=req, silent=hlist.silent)
[Fri Jan 30 06:09:48 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1229, in _process_target\n    result = _execute_target(config, req, object, arg)
[Fri Jan 30 06:09:48 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1128, in _execute_target\n    result = object(arg)
[Fri Jan 30 06:09:48 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/modpython.py", line 228, in handler\n    return ModPythonHandler()(req)
[Fri Jan 30 06:09:48 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/modpython.py", line 191, in __call__\n    self.load_middleware()
[Fri Jan 30 06:09:48 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/base.py", line 44, in load_middleware\n    raise exceptions.ImproperlyConfigured, 'Middleware module "%s" does not define a "%s" class' % (mw_module, mw_classname)
[Fri Jan 30 06:09:48 2009] [error] [client 127.0.0.1] ImproperlyConfigured: Middleware module "django.contrib.flatpages.middleware" does not define a "FlatPageFallbackMiddleware" class
[Fri Jan 30 06:09:51 2009] [error] [client 127.0.0.1] mod_python (pid=6306, interpreter='web63.webfaction.com', phase='PythonHandler', handler='django.core.handlers.modpython'): Application error
[Fri Jan 30 06:09:51 2009] [error] [client 127.0.0.1] ServerName: 'web63.webfaction.com'
[Fri Jan 30 06:09:51 2009] [error] [client 127.0.0.1] DocumentRoot: '/etc/httpd/htdocs'
[Fri Jan 30 06:09:51 2009] [error] [client 127.0.0.1] URI: '/admin/'
[Fri Jan 30 06:09:51 2009] [error] [client 127.0.0.1] Location: '/'
[Fri Jan 30 06:09:51 2009] [error] [client 127.0.0.1] Directory: None
[Fri Jan 30 06:09:51 2009] [error] [client 127.0.0.1] Filename: '/etc/httpd/htdocs'
[Fri Jan 30 06:09:51 2009] [error] [client 127.0.0.1] PathInfo: '/admin/'
[Fri Jan 30 06:09:51 2009] [error] [client 127.0.0.1] Traceback (most recent call last):
[Fri Jan 30 06:09:51 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1537, in HandlerDispatch\n    default=default_handler, arg=req, silent=hlist.silent)
[Fri Jan 30 06:09:51 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1229, in _process_target\n    result = _execute_target(config, req, object, arg)
[Fri Jan 30 06:09:51 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1128, in _execute_target\n    result = object(arg)
[Fri Jan 30 06:09:51 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/modpython.py", line 228, in handler\n    return ModPythonHandler()(req)
[Fri Jan 30 06:09:51 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/modpython.py", line 191, in __call__\n    self.load_middleware()
[Fri Jan 30 06:09:51 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/base.py", line 44, in load_middleware\n    raise exceptions.ImproperlyConfigured, 'Middleware module "%s" does not define a "%s" class' % (mw_module, mw_classname)
[Fri Jan 30 06:09:51 2009] [error] [client 127.0.0.1] ImproperlyConfigured: Middleware module "django.contrib.flatpages.middleware" does not define a "FlatPageFallbackMiddleware" class
[Fri Jan 30 06:09:52 2009] [error] [client 127.0.0.1] mod_python (pid=6307, interpreter='web63.webfaction.com', phase='PythonHandler', handler='django.core.handlers.modpython'): Application error
[Fri Jan 30 06:09:52 2009] [error] [client 127.0.0.1] ServerName: 'web63.webfaction.com'
[Fri Jan 30 06:09:52 2009] [error] [client 127.0.0.1] DocumentRoot: '/etc/httpd/htdocs'
[Fri Jan 30 06:09:52 2009] [error] [client 127.0.0.1] URI: '/admin/'
[Fri Jan 30 06:09:52 2009] [error] [client 127.0.0.1] Location: '/'
[Fri Jan 30 06:09:52 2009] [error] [client 127.0.0.1] Directory: None
[Fri Jan 30 06:09:52 2009] [error] [client 127.0.0.1] Filename: '/etc/httpd/htdocs'
[Fri Jan 30 06:09:52 2009] [error] [client 127.0.0.1] PathInfo: '/admin/'
[Fri Jan 30 06:09:52 2009] [error] [client 127.0.0.1] Traceback (most recent call last):
[Fri Jan 30 06:09:52 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1537, in HandlerDispatch\n    default=default_handler, arg=req, silent=hlist.silent)
[Fri Jan 30 06:09:52 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1229, in _process_target\n    result = _execute_target(config, req, object, arg)
[Fri Jan 30 06:09:52 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1128, in _execute_target\n    result = object(arg)
[Fri Jan 30 06:09:52 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/modpython.py", line 228, in handler\n    return ModPythonHandler()(req)
[Fri Jan 30 06:09:52 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/modpython.py", line 191, in __call__\n    self.load_middleware()
[Fri Jan 30 06:09:52 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/base.py", line 44, in load_middleware\n    raise exceptions.ImproperlyConfigured, 'Middleware module "%s" does not define a "%s" class' % (mw_module, mw_classname)
[Fri Jan 30 06:09:52 2009] [error] [client 127.0.0.1] ImproperlyConfigured: Middleware module "django.contrib.flatpages.middleware" does not define a "FlatPageFallbackMiddleware" class
[Fri Jan 30 00:10:06 2009] [notice] caught SIGTERM, shutting down
[Fri Jan 30 00:10:09 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Fri Jan 30 00:10:09 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Fri Jan 30 00:10:09 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Fri Jan 30 00:10:09 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Fri Jan 30 00:10:09 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Fri Jan 30 00:10:09 2009] [notice] mod_python: using mutex_directory /tmp 
[Fri Jan 30 00:10:09 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Fri Jan 30 00:10:10 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Fri Jan 30 06:10:12 2009] [error] [client 127.0.0.1] mod_python (pid=6420, interpreter='web63.webfaction.com', phase='PythonHandler', handler='django.core.handlers.modpython'): Application error
[Fri Jan 30 06:10:12 2009] [error] [client 127.0.0.1] ServerName: 'web63.webfaction.com'
[Fri Jan 30 06:10:12 2009] [error] [client 127.0.0.1] DocumentRoot: '/etc/httpd/htdocs'
[Fri Jan 30 06:10:12 2009] [error] [client 127.0.0.1] URI: '/notes/'
[Fri Jan 30 06:10:12 2009] [error] [client 127.0.0.1] Location: '/'
[Fri Jan 30 06:10:12 2009] [error] [client 127.0.0.1] Directory: None
[Fri Jan 30 06:10:12 2009] [error] [client 127.0.0.1] Filename: '/etc/httpd/htdocs'
[Fri Jan 30 06:10:12 2009] [error] [client 127.0.0.1] PathInfo: '/notes/'
[Fri Jan 30 06:10:12 2009] [error] [client 127.0.0.1] Traceback (most recent call last):
[Fri Jan 30 06:10:12 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1537, in HandlerDispatch\n    default=default_handler, arg=req, silent=hlist.silent)
[Fri Jan 30 06:10:12 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1229, in _process_target\n    result = _execute_target(config, req, object, arg)
[Fri Jan 30 06:10:12 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1128, in _execute_target\n    result = object(arg)
[Fri Jan 30 06:10:12 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/modpython.py", line 228, in handler\n    return ModPythonHandler()(req)
[Fri Jan 30 06:10:12 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/modpython.py", line 191, in __call__\n    self.load_middleware()
[Fri Jan 30 06:10:12 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/base.py", line 44, in load_middleware\n    raise exceptions.ImproperlyConfigured, 'Middleware module "%s" does not define a "%s" class' % (mw_module, mw_classname)
[Fri Jan 30 06:10:12 2009] [error] [client 127.0.0.1] ImproperlyConfigured: Middleware module "django.contrib.flatpages.middleware" does not define a "FlatPageFallbackMiddleware" class
[Fri Jan 30 06:10:15 2009] [error] [client 127.0.0.1] mod_python (pid=6421, interpreter='web63.webfaction.com', phase='PythonHandler', handler='django.core.handlers.modpython'): Application error
[Fri Jan 30 06:10:15 2009] [error] [client 127.0.0.1] ServerName: 'web63.webfaction.com'
[Fri Jan 30 06:10:15 2009] [error] [client 127.0.0.1] DocumentRoot: '/etc/httpd/htdocs'
[Fri Jan 30 06:10:15 2009] [error] [client 127.0.0.1] URI: '/notes/'
[Fri Jan 30 06:10:15 2009] [error] [client 127.0.0.1] Location: '/'
[Fri Jan 30 06:10:15 2009] [error] [client 127.0.0.1] Directory: None
[Fri Jan 30 06:10:15 2009] [error] [client 127.0.0.1] Filename: '/etc/httpd/htdocs'
[Fri Jan 30 06:10:15 2009] [error] [client 127.0.0.1] PathInfo: '/notes/'
[Fri Jan 30 06:10:15 2009] [error] [client 127.0.0.1] Traceback (most recent call last):
[Fri Jan 30 06:10:15 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1537, in HandlerDispatch\n    default=default_handler, arg=req, silent=hlist.silent)
[Fri Jan 30 06:10:15 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1229, in _process_target\n    result = _execute_target(config, req, object, arg)
[Fri Jan 30 06:10:15 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1128, in _execute_target\n    result = object(arg)
[Fri Jan 30 06:10:15 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/modpython.py", line 228, in handler\n    return ModPythonHandler()(req)
[Fri Jan 30 06:10:15 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/modpython.py", line 191, in __call__\n    self.load_middleware()
[Fri Jan 30 06:10:15 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/base.py", line 44, in load_middleware\n    raise exceptions.ImproperlyConfigured, 'Middleware module "%s" does not define a "%s" class' % (mw_module, mw_classname)
[Fri Jan 30 06:10:15 2009] [error] [client 127.0.0.1] ImproperlyConfigured: Middleware module "django.contrib.flatpages.middleware" does not define a "FlatPageFallbackMiddleware" class
[Fri Jan 30 00:10:44 2009] [notice] caught SIGTERM, shutting down
[Fri Jan 30 00:10:47 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Fri Jan 30 00:10:47 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Fri Jan 30 00:10:47 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Fri Jan 30 00:10:47 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Fri Jan 30 00:10:47 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Fri Jan 30 00:10:47 2009] [notice] mod_python: using mutex_directory /tmp 
[Fri Jan 30 00:10:47 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Fri Jan 30 00:10:48 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Fri Jan 30 00:11:33 2009] [notice] caught SIGTERM, shutting down
[Fri Jan 30 00:11:36 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Fri Jan 30 00:11:36 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Fri Jan 30 00:11:36 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Fri Jan 30 00:11:36 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Fri Jan 30 00:11:36 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Fri Jan 30 00:11:36 2009] [notice] mod_python: using mutex_directory /tmp 
[Fri Jan 30 00:11:36 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Fri Jan 30 00:11:37 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Fri Jan 30 00:11:58 2009] [notice] caught SIGTERM, shutting down
[Fri Jan 30 00:12:01 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Fri Jan 30 00:12:01 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Fri Jan 30 00:12:01 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Fri Jan 30 00:12:01 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Fri Jan 30 00:12:01 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Fri Jan 30 00:12:01 2009] [notice] mod_python: using mutex_directory /tmp 
[Fri Jan 30 00:12:01 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Fri Jan 30 00:12:02 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Fri Jan 30 00:15:13 2009] [notice] caught SIGTERM, shutting down
[Fri Jan 30 00:15:16 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Fri Jan 30 00:15:16 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Fri Jan 30 00:15:16 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Fri Jan 30 00:15:16 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Fri Jan 30 00:15:16 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Fri Jan 30 00:15:16 2009] [notice] mod_python: using mutex_directory /tmp 
[Fri Jan 30 00:15:16 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Fri Jan 30 00:15:17 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Fri Jan 30 00:17:06 2009] [notice] caught SIGTERM, shutting down
[Fri Jan 30 00:17:09 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Fri Jan 30 00:17:09 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Fri Jan 30 00:17:09 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Fri Jan 30 00:17:09 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Fri Jan 30 00:17:09 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Fri Jan 30 00:17:09 2009] [notice] mod_python: using mutex_directory /tmp 
[Fri Jan 30 00:17:09 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Fri Jan 30 00:17:10 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Fri Jan 30 00:22:48 2009] [notice] caught SIGTERM, shutting down
[Fri Jan 30 00:22:51 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Fri Jan 30 00:22:51 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Fri Jan 30 00:22:51 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Fri Jan 30 00:22:51 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Fri Jan 30 00:22:51 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Fri Jan 30 00:22:51 2009] [notice] mod_python: using mutex_directory /tmp 
[Fri Jan 30 00:22:51 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Fri Jan 30 00:22:52 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Sun Feb 01 01:55:51 2009] [notice] caught SIGTERM, shutting down
[Sun Feb 01 01:55:54 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Sun Feb 01 01:55:54 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Sun Feb 01 01:55:54 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Sun Feb 01 01:55:54 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Sun Feb 01 01:55:54 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Sun Feb 01 01:55:54 2009] [notice] mod_python: using mutex_directory /tmp 
[Sun Feb 01 01:55:54 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Sun Feb 01 01:55:55 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Sun Feb 01 01:57:23 2009] [notice] caught SIGTERM, shutting down
[Sun Feb 01 01:57:26 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Sun Feb 01 01:57:26 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Sun Feb 01 01:57:26 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Sun Feb 01 01:57:26 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Sun Feb 01 01:57:26 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Sun Feb 01 01:57:26 2009] [notice] mod_python: using mutex_directory /tmp 
[Sun Feb 01 01:57:27 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Sun Feb 01 01:57:28 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Sun Feb 01 02:24:12 2009] [notice] caught SIGTERM, shutting down
[Sun Feb 01 02:24:15 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Sun Feb 01 02:24:15 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Sun Feb 01 02:24:15 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Sun Feb 01 02:24:15 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Sun Feb 01 02:24:15 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Sun Feb 01 02:24:15 2009] [notice] mod_python: using mutex_directory /tmp 
[Sun Feb 01 02:24:15 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Sun Feb 01 02:24:16 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Sun Feb 01 02:34:39 2009] [notice] caught SIGTERM, shutting down
[Sun Feb 01 02:34:42 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Sun Feb 01 02:34:42 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Sun Feb 01 02:34:42 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Sun Feb 01 02:34:42 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Sun Feb 01 02:34:42 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Sun Feb 01 02:34:42 2009] [notice] mod_python: using mutex_directory /tmp 
[Sun Feb 01 02:34:42 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Sun Feb 01 02:34:43 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Sun Feb 01 19:17:01 2009] [notice] caught SIGTERM, shutting down
[Sun Feb 01 19:17:04 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Sun Feb 01 19:17:04 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Sun Feb 01 19:17:04 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Sun Feb 01 19:17:04 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Sun Feb 01 19:17:04 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Sun Feb 01 19:17:04 2009] [notice] mod_python: using mutex_directory /tmp 
[Sun Feb 01 19:17:04 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Sun Feb 01 19:17:05 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Sun Feb 01 19:34:47 2009] [notice] caught SIGTERM, shutting down
[Sun Feb 01 19:34:50 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Sun Feb 01 19:34:50 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Sun Feb 01 19:34:50 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Sun Feb 01 19:34:50 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Sun Feb 01 19:34:50 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Sun Feb 01 19:34:50 2009] [notice] mod_python: using mutex_directory /tmp 
[Sun Feb 01 19:34:50 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Sun Feb 01 19:34:51 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Sun Feb 01 19:53:02 2009] [notice] caught SIGTERM, shutting down
[Sun Feb 01 19:53:05 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Sun Feb 01 19:53:05 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Sun Feb 01 19:53:05 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Sun Feb 01 19:53:05 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Sun Feb 01 19:53:05 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Sun Feb 01 19:53:05 2009] [notice] mod_python: using mutex_directory /tmp 
[Sun Feb 01 19:53:05 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Sun Feb 01 19:53:06 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Sun Feb 01 22:47:55 2009] [notice] caught SIGTERM, shutting down
[Sun Feb 01 22:47:58 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Sun Feb 01 22:47:58 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Sun Feb 01 22:47:58 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Sun Feb 01 22:47:58 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Sun Feb 01 22:47:58 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Sun Feb 01 22:47:58 2009] [notice] mod_python: using mutex_directory /tmp 
[Sun Feb 01 22:47:58 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Sun Feb 01 22:47:59 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Sun Feb 01 23:43:27 2009] [notice] caught SIGTERM, shutting down
[Sun Feb 01 23:43:30 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Sun Feb 01 23:43:30 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Sun Feb 01 23:43:30 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Sun Feb 01 23:43:30 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Sun Feb 01 23:43:30 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Sun Feb 01 23:43:30 2009] [notice] mod_python: using mutex_directory /tmp 
[Sun Feb 01 23:43:30 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Sun Feb 01 23:43:31 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Sun Feb 01 23:44:00 2009] [notice] caught SIGTERM, shutting down
[Sun Feb 01 23:44:03 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Sun Feb 01 23:44:03 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Sun Feb 01 23:44:03 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Sun Feb 01 23:44:03 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Sun Feb 01 23:44:03 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Sun Feb 01 23:44:03 2009] [notice] mod_python: using mutex_directory /tmp 
[Sun Feb 01 23:44:03 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Sun Feb 01 23:44:04 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Mon Feb 02 01:09:03 2009] [notice] caught SIGTERM, shutting down
[Mon Feb 02 01:09:06 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Mon Feb 02 01:09:06 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Mon Feb 02 01:09:06 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Mon Feb 02 01:09:06 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Mon Feb 02 01:09:06 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Mon Feb 02 01:09:06 2009] [notice] mod_python: using mutex_directory /tmp 
[Mon Feb 02 01:09:06 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Mon Feb 02 01:09:07 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Mon Feb 02 01:09:11 2009] [notice] caught SIGTERM, shutting down
[Mon Feb 02 01:09:14 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Mon Feb 02 01:09:14 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Mon Feb 02 01:09:14 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Mon Feb 02 01:09:14 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Mon Feb 02 01:09:14 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Mon Feb 02 01:09:14 2009] [notice] mod_python: using mutex_directory /tmp 
[Mon Feb 02 01:09:14 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Mon Feb 02 01:09:15 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Mon Feb 02 02:41:51 2009] [notice] caught SIGTERM, shutting down
[Mon Feb 02 02:41:54 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Mon Feb 02 02:41:54 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Mon Feb 02 02:41:54 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Mon Feb 02 02:41:54 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Mon Feb 02 02:41:54 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Mon Feb 02 02:41:54 2009] [notice] mod_python: using mutex_directory /tmp 
[Mon Feb 02 02:41:54 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Mon Feb 02 02:41:55 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Mon Feb 02 14:24:52 2009] [notice] caught SIGTERM, shutting down
[Mon Feb 02 14:24:55 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Mon Feb 02 14:24:55 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Mon Feb 02 14:24:55 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Mon Feb 02 14:24:55 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Mon Feb 02 14:24:55 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Mon Feb 02 14:24:55 2009] [notice] mod_python: using mutex_directory /tmp 
[Mon Feb 02 14:24:55 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Mon Feb 02 14:24:56 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Mon Feb 02 14:25:34 2009] [notice] caught SIGTERM, shutting down
[Mon Feb 02 14:25:37 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Mon Feb 02 14:25:37 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Mon Feb 02 14:25:37 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Mon Feb 02 14:25:37 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Mon Feb 02 14:25:37 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Mon Feb 02 14:25:37 2009] [notice] mod_python: using mutex_directory /tmp 
[Mon Feb 02 14:25:37 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Mon Feb 02 14:25:38 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Mon Feb 02 14:31:28 2009] [notice] caught SIGTERM, shutting down
[Mon Feb 02 14:31:31 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Mon Feb 02 14:31:31 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Mon Feb 02 14:31:31 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Mon Feb 02 14:31:31 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Mon Feb 02 14:31:31 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Mon Feb 02 14:31:31 2009] [notice] mod_python: using mutex_directory /tmp 
[Mon Feb 02 14:31:31 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Mon Feb 02 14:31:32 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Mon Feb 02 14:32:45 2009] [notice] caught SIGTERM, shutting down
[Mon Feb 02 14:32:48 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Mon Feb 02 14:32:48 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Mon Feb 02 14:32:48 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Mon Feb 02 14:32:48 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Mon Feb 02 14:32:48 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Mon Feb 02 14:32:48 2009] [notice] mod_python: using mutex_directory /tmp 
[Mon Feb 02 14:32:48 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Mon Feb 02 14:32:49 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Mon Feb 02 20:40:43 2009] [error] [client 127.0.0.1] mod_python (pid=20775, interpreter='web63.webfaction.com', phase='PythonHandler', handler='django.core.handlers.modpython'): Application error
[Mon Feb 02 20:40:43 2009] [error] [client 127.0.0.1] ServerName: 'web63.webfaction.com'
[Mon Feb 02 20:40:43 2009] [error] [client 127.0.0.1] DocumentRoot: '/etc/httpd/htdocs'
[Mon Feb 02 20:40:43 2009] [error] [client 127.0.0.1] URI: '/favicon.ico'
[Mon Feb 02 20:40:43 2009] [error] [client 127.0.0.1] Location: '/'
[Mon Feb 02 20:40:43 2009] [error] [client 127.0.0.1] Directory: None
[Mon Feb 02 20:40:43 2009] [error] [client 127.0.0.1] Filename: '/etc/httpd/htdocs'
[Mon Feb 02 20:40:43 2009] [error] [client 127.0.0.1] PathInfo: '/favicon.ico'
[Mon Feb 02 20:40:43 2009] [error] [client 127.0.0.1] Traceback (most recent call last):
[Mon Feb 02 20:40:43 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1537, in HandlerDispatch\n    default=default_handler, arg=req, silent=hlist.silent)
[Mon Feb 02 20:40:43 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1229, in _process_target\n    result = _execute_target(config, req, object, arg)
[Mon Feb 02 20:40:43 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1128, in _execute_target\n    result = object(arg)
[Mon Feb 02 20:40:43 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/modpython.py", line 228, in handler\n    return ModPythonHandler()(req)
[Mon Feb 02 20:40:43 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/modpython.py", line 201, in __call__\n    response = self.get_response(request)
[Mon Feb 02 20:40:43 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/base.py", line 67, in get_response\n    response = middleware_method(request)
[Mon Feb 02 20:40:43 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/middleware/common.py", line 56, in process_request\n    if (not _is_valid_path(request.path_info) and
[Mon Feb 02 20:40:43 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/middleware/common.py", line 142, in _is_valid_path\n    urlresolvers.resolve(path)
[Mon Feb 02 20:40:43 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/urlresolvers.py", line 246, in resolve\n    return get_resolver(urlconf).resolve(path)
[Mon Feb 02 20:40:43 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/urlresolvers.py", line 179, in resolve\n    for pattern in self.urlconf_module.urlpatterns:
[Mon Feb 02 20:40:43 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/urlresolvers.py", line 198, in _get_urlconf_module\n    self._urlconf_module = __import__(self.urlconf_name, {}, {}, [''])
[Mon Feb 02 20:40:43 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/jquery_project/urls.py", line 5, in <module>\n    admin.autodiscover()
[Mon Feb 02 20:40:43 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/contrib/admin/__init__.py", line 40, in autodiscover\n    __import__("%s.admin" % app)
[Mon Feb 02 20:40:43 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/contrib/auth/admin.py", line 10, in <module>\n    from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AdminPasswordChangeForm
[Mon Feb 02 20:40:43 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/contrib/auth/forms.py", line 10, in <module>\n    class UserCreationForm(forms.ModelForm):
[Mon Feb 02 20:40:43 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/contrib/auth/forms.py", line 16, in UserCreationForm\n    error_message = _("This value must contain only letters, numbers and underscores."))
[Mon Feb 02 20:40:43 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/forms/fields.py", line 400, in __init__\n    if error_message:
[Mon Feb 02 20:40:43 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/utils/functional.py", line 188, in __wrapper__\n    res = self.__func(*self.__args, **self.__kw)
[Mon Feb 02 20:40:43 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/utils/translation/__init__.py", line 62, in ugettext\n    return real_ugettext(message)
[Mon Feb 02 20:40:43 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/utils/translation/__init__.py", line 43, in delayed_loader\n    return g['real_%s' % caller](*args, **kwargs)
[Mon Feb 02 20:40:43 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/utils/translation/trans_real.py", line 290, in ugettext\n    return do_translate(message, 'ugettext')
[Mon Feb 02 20:40:43 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/utils/translation/trans_real.py", line 280, in do_translate\n    _default = translation(settings.LANGUAGE_CODE)
[Mon Feb 02 20:40:43 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/utils/translation/trans_real.py", line 198, in translation\n    default_translation = _fetch(settings.LANGUAGE_CODE)
[Mon Feb 02 20:40:43 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/utils/translation/trans_real.py", line 181, in _fetch\n    app = getattr(__import__(appname[:p], {}, {}, [appname[p+1:]]), appname[p+1:])
[Mon Feb 02 20:40:43 2009] [error] [client 127.0.0.1] ImportError: No module named syncr
[Mon Feb 02 20:42:47 2009] [error] [client 127.0.0.1] mod_python (pid=20776, interpreter='web63.webfaction.com', phase='PythonHandler', handler='django.core.handlers.modpython'): Application error
[Mon Feb 02 20:42:47 2009] [error] [client 127.0.0.1] ServerName: 'web63.webfaction.com'
[Mon Feb 02 20:42:47 2009] [error] [client 127.0.0.1] DocumentRoot: '/etc/httpd/htdocs'
[Mon Feb 02 20:42:47 2009] [error] [client 127.0.0.1] URI: '/admin/portfolio/category/'
[Mon Feb 02 20:42:47 2009] [error] [client 127.0.0.1] Location: '/'
[Mon Feb 02 20:42:47 2009] [error] [client 127.0.0.1] Directory: None
[Mon Feb 02 20:42:47 2009] [error] [client 127.0.0.1] Filename: '/etc/httpd/htdocs'
[Mon Feb 02 20:42:47 2009] [error] [client 127.0.0.1] PathInfo: '/admin/portfolio/category/'
[Mon Feb 02 20:42:48 2009] [error] [client 127.0.0.1] Traceback (most recent call last):
[Mon Feb 02 20:42:48 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1537, in HandlerDispatch\n    default=default_handler, arg=req, silent=hlist.silent)
[Mon Feb 02 20:42:48 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1229, in _process_target\n    result = _execute_target(config, req, object, arg)
[Mon Feb 02 20:42:48 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1128, in _execute_target\n    result = object(arg)
[Mon Feb 02 20:42:48 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/modpython.py", line 228, in handler\n    return ModPythonHandler()(req)
[Mon Feb 02 20:42:48 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/modpython.py", line 201, in __call__\n    response = self.get_response(request)
[Mon Feb 02 20:42:48 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/base.py", line 128, in get_response\n    return self.handle_uncaught_exception(request, resolver, exc_info)
[Mon Feb 02 20:42:48 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/base.py", line 148, in handle_uncaught_exception\n    return debug.technical_500_response(request, *exc_info)
[Mon Feb 02 20:42:48 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/views/debug.py", line 39, in technical_500_response\n    html = reporter.get_traceback_html()
[Mon Feb 02 20:42:48 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/views/debug.py", line 113, in get_traceback_html\n    return t.render(c)
[Mon Feb 02 20:42:48 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/template/__init__.py", line 176, in render\n    return self.nodelist.render(context)
[Mon Feb 02 20:42:48 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/template/__init__.py", line 768, in render\n    bits.append(self.render_node(node, context))
[Mon Feb 02 20:42:48 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/template/debug.py", line 81, in render_node\n    raise wrapped
[Mon Feb 02 20:42:48 2009] [error] [client 127.0.0.1] TemplateSyntaxError: Caught an exception while rendering: No module named syncr\n\nOriginal Traceback (most recent call last):\n  File "/home/gongura/webapps/django/lib/python2.5/django/template/debug.py", line 71, in render_node\n    result = node.render(context)\n  File "/home/gongura/webapps/django/lib/python2.5/django/template/debug.py", line 87, in render\n    output = force_unicode(self.filter_expression.resolve(context))\n  File "/home/gongura/webapps/django/lib/python2.5/django/template/__init__.py", line 559, in resolve\n    new_obj = func(obj, *arg_vals)\n  File "/home/gongura/webapps/django/lib/python2.5/django/template/defaultfilters.py", line 668, in date\n    return format(value, arg)\n  File "/home/gongura/webapps/django/lib/python2.5/django/utils/dateformat.py", line 264, in format\n    return df.format(format_string)\n  File "/home/gongura/webapps/django/lib/python2.5/django/utils/dateformat.py", line 29, in format\n    pieces.append(force_unicode(getattr(self, piece)()))\n  File "/home/gongura/webapps/django/lib/python2.5/django/utils/dateformat.py", line 174, in r\n    return self.format('D, j M Y H:i:s O')\n  File "/home/gongura/webapps/django/lib/python2.5/django/utils/dateformat.py", line 29, in format\n    pieces.append(force_unicode(getattr(self, piece)()))\n  File "/home/gongura/webapps/django/lib/python2.5/django/utils/encoding.py", line 49, in force_unicode\n    s = unicode(s)\n  File "/home/gongura/webapps/django/lib/python2.5/django/utils/functional.py", line 201, in __unicode_cast\n    return self.__func(*self.__args, **self.__kw)\n  File "/home/gongura/webapps/django/lib/python2.5/django/utils/translation/__init__.py", line 62, in ugettext\n    return real_ugettext(message)\n  File "/home/gongura/webapps/django/lib/python2.5/django/utils/translation/trans_real.py", line 290, in ugettext\n    return do_translate(message, 'ugettext')\n  File "/home/gongura/webapps/django/lib/python2.5/django/utils/translation/trans_real.py", line 280, in do_translate\n    _default = translation(settings.LANGUAGE_CODE)\n  File "/home/gongura/webapps/django/lib/python2.5/django/utils/translation/trans_real.py", line 198, in translation\n    default_translation = _fetch(settings.LANGUAGE_CODE)\n  File "/home/gongura/webapps/django/lib/python2.5/django/utils/translation/trans_real.py", line 181, in _fetch\n    app = getattr(__import__(appname[:p], {}, {}, [appname[p+1:]]), appname[p+1:])\nImportError: No module named syncr\n
[Mon Feb 02 20:42:49 2009] [error] [client 127.0.0.1] mod_python (pid=20775, interpreter='web63.webfaction.com', phase='PythonHandler', handler='django.core.handlers.modpython'): Application error
[Mon Feb 02 20:42:49 2009] [error] [client 127.0.0.1] ServerName: 'web63.webfaction.com'
[Mon Feb 02 20:42:49 2009] [error] [client 127.0.0.1] DocumentRoot: '/etc/httpd/htdocs'
[Mon Feb 02 20:42:49 2009] [error] [client 127.0.0.1] URI: '/admin/'
[Mon Feb 02 20:42:49 2009] [error] [client 127.0.0.1] Location: '/'
[Mon Feb 02 20:42:49 2009] [error] [client 127.0.0.1] Directory: None
[Mon Feb 02 20:42:49 2009] [error] [client 127.0.0.1] Filename: '/etc/httpd/htdocs'
[Mon Feb 02 20:42:49 2009] [error] [client 127.0.0.1] PathInfo: '/admin/'
[Mon Feb 02 20:42:49 2009] [error] [client 127.0.0.1] Traceback (most recent call last):
[Mon Feb 02 20:42:49 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1537, in HandlerDispatch\n    default=default_handler, arg=req, silent=hlist.silent)
[Mon Feb 02 20:42:49 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1229, in _process_target\n    result = _execute_target(config, req, object, arg)
[Mon Feb 02 20:42:49 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1128, in _execute_target\n    result = object(arg)
[Mon Feb 02 20:42:49 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/modpython.py", line 228, in handler\n    return ModPythonHandler()(req)
[Mon Feb 02 20:42:49 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/modpython.py", line 201, in __call__\n    response = self.get_response(request)
[Mon Feb 02 20:42:49 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/base.py", line 128, in get_response\n    return self.handle_uncaught_exception(request, resolver, exc_info)
[Mon Feb 02 20:42:49 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/base.py", line 148, in handle_uncaught_exception\n    return debug.technical_500_response(request, *exc_info)
[Mon Feb 02 20:42:49 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/views/debug.py", line 39, in technical_500_response\n    html = reporter.get_traceback_html()
[Mon Feb 02 20:42:49 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/views/debug.py", line 113, in get_traceback_html\n    return t.render(c)
[Mon Feb 02 20:42:49 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/template/__init__.py", line 176, in render\n    return self.nodelist.render(context)
[Mon Feb 02 20:42:49 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/template/__init__.py", line 768, in render\n    bits.append(self.render_node(node, context))
[Mon Feb 02 20:42:49 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/template/debug.py", line 81, in render_node\n    raise wrapped
[Mon Feb 02 20:42:49 2009] [error] [client 127.0.0.1] TemplateSyntaxError: Caught an exception while rendering: No module named syncr\n\nOriginal Traceback (most recent call last):\n  File "/home/gongura/webapps/django/lib/python2.5/django/template/debug.py", line 71, in render_node\n    result = node.render(context)\n  File "/home/gongura/webapps/django/lib/python2.5/django/template/debug.py", line 87, in render\n    output = force_unicode(self.filter_expression.resolve(context))\n  File "/home/gongura/webapps/django/lib/python2.5/django/template/__init__.py", line 559, in resolve\n    new_obj = func(obj, *arg_vals)\n  File "/home/gongura/webapps/django/lib/python2.5/django/template/defaultfilters.py", line 668, in date\n    return format(value, arg)\n  File "/home/gongura/webapps/django/lib/python2.5/django/utils/dateformat.py", line 264, in format\n    return df.format(format_string)\n  File "/home/gongura/webapps/django/lib/python2.5/django/utils/dateformat.py", line 29, in format\n    pieces.append(force_unicode(getattr(self, piece)()))\n  File "/home/gongura/webapps/django/lib/python2.5/django/utils/dateformat.py", line 174, in r\n    return self.format('D, j M Y H:i:s O')\n  File "/home/gongura/webapps/django/lib/python2.5/django/utils/dateformat.py", line 29, in format\n    pieces.append(force_unicode(getattr(self, piece)()))\n  File "/home/gongura/webapps/django/lib/python2.5/django/utils/encoding.py", line 49, in force_unicode\n    s = unicode(s)\n  File "/home/gongura/webapps/django/lib/python2.5/django/utils/functional.py", line 201, in __unicode_cast\n    return self.__func(*self.__args, **self.__kw)\n  File "/home/gongura/webapps/django/lib/python2.5/django/utils/translation/__init__.py", line 62, in ugettext\n    return real_ugettext(message)\n  File "/home/gongura/webapps/django/lib/python2.5/django/utils/translation/trans_real.py", line 290, in ugettext\n    return do_translate(message, 'ugettext')\n  File "/home/gongura/webapps/django/lib/python2.5/django/utils/translation/trans_real.py", line 280, in do_translate\n    _default = translation(settings.LANGUAGE_CODE)\n  File "/home/gongura/webapps/django/lib/python2.5/django/utils/translation/trans_real.py", line 198, in translation\n    default_translation = _fetch(settings.LANGUAGE_CODE)\n  File "/home/gongura/webapps/django/lib/python2.5/django/utils/translation/trans_real.py", line 181, in _fetch\n    app = getattr(__import__(appname[:p], {}, {}, [appname[p+1:]]), appname[p+1:])\nImportError: No module named syncr\n
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1] mod_python (pid=20776, interpreter='web63.webfaction.com', phase='PythonHandler', handler='django.core.handlers.modpython'): Application error
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1] ServerName: 'web63.webfaction.com'
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1] DocumentRoot: '/etc/httpd/htdocs'
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1] URI: '/favicon.ico'
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1] Location: '/'
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1] Directory: None
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1] Filename: '/etc/httpd/htdocs'
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1] PathInfo: '/favicon.ico'
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1] Traceback (most recent call last):
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1537, in HandlerDispatch\n    default=default_handler, arg=req, silent=hlist.silent)
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1229, in _process_target\n    result = _execute_target(config, req, object, arg)
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1128, in _execute_target\n    result = object(arg)
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/modpython.py", line 228, in handler\n    return ModPythonHandler()(req)
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/modpython.py", line 201, in __call__\n    response = self.get_response(request)
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/base.py", line 67, in get_response\n    response = middleware_method(request)
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/middleware/common.py", line 56, in process_request\n    if (not _is_valid_path(request.path_info) and
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/middleware/common.py", line 142, in _is_valid_path\n    urlresolvers.resolve(path)
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/urlresolvers.py", line 246, in resolve\n    return get_resolver(urlconf).resolve(path)
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/urlresolvers.py", line 179, in resolve\n    for pattern in self.urlconf_module.urlpatterns:
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/urlresolvers.py", line 198, in _get_urlconf_module\n    self._urlconf_module = __import__(self.urlconf_name, {}, {}, [''])
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/jquery_project/urls.py", line 5, in <module>\n    admin.autodiscover()
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/contrib/admin/__init__.py", line 40, in autodiscover\n    __import__("%s.admin" % app)
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/contrib/auth/admin.py", line 10, in <module>\n    from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AdminPasswordChangeForm
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/contrib/auth/forms.py", line 10, in <module>\n    class UserCreationForm(forms.ModelForm):
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/contrib/auth/forms.py", line 16, in UserCreationForm\n    error_message = _("This value must contain only letters, numbers and underscores."))
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/forms/fields.py", line 400, in __init__\n    if error_message:
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/utils/functional.py", line 188, in __wrapper__\n    res = self.__func(*self.__args, **self.__kw)
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/utils/translation/__init__.py", line 62, in ugettext\n    return real_ugettext(message)
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/utils/translation/trans_real.py", line 290, in ugettext\n    return do_translate(message, 'ugettext')
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/utils/translation/trans_real.py", line 280, in do_translate\n    _default = translation(settings.LANGUAGE_CODE)
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/utils/translation/trans_real.py", line 198, in translation\n    default_translation = _fetch(settings.LANGUAGE_CODE)
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/utils/translation/trans_real.py", line 181, in _fetch\n    app = getattr(__import__(appname[:p], {}, {}, [appname[p+1:]]), appname[p+1:])
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1] ImportError: No module named syncr
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1] mod_python (pid=20775, interpreter='web63.webfaction.com', phase='PythonHandler', handler='django.core.handlers.modpython'): Application error
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1] ServerName: 'web63.webfaction.com'
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1] DocumentRoot: '/etc/httpd/htdocs'
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1] URI: '/root/'
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1] Location: '/'
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1] Directory: None
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1] Filename: '/etc/httpd/htdocs'
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1] PathInfo: '/root/'
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1] Traceback (most recent call last):
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1537, in HandlerDispatch\n    default=default_handler, arg=req, silent=hlist.silent)
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1229, in _process_target\n    result = _execute_target(config, req, object, arg)
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/mod_python/importer.py", line 1128, in _execute_target\n    result = object(arg)
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/modpython.py", line 228, in handler\n    return ModPythonHandler()(req)
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/modpython.py", line 201, in __call__\n    response = self.get_response(request)
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/base.py", line 128, in get_response\n    return self.handle_uncaught_exception(request, resolver, exc_info)
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/core/handlers/base.py", line 148, in handle_uncaught_exception\n    return debug.technical_500_response(request, *exc_info)
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/views/debug.py", line 39, in technical_500_response\n    html = reporter.get_traceback_html()
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/views/debug.py", line 113, in get_traceback_html\n    return t.render(c)
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/template/__init__.py", line 176, in render\n    return self.nodelist.render(context)
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/template/__init__.py", line 768, in render\n    bits.append(self.render_node(node, context))
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1]   File "/home/gongura/webapps/django/lib/python2.5/django/template/debug.py", line 81, in render_node\n    raise wrapped
[Mon Feb 02 20:43:01 2009] [error] [client 127.0.0.1] TemplateSyntaxError: Caught an exception while rendering: No module named syncr\n\nOriginal Traceback (most recent call last):\n  File "/home/gongura/webapps/django/lib/python2.5/django/template/debug.py", line 71, in render_node\n    result = node.render(context)\n  File "/home/gongura/webapps/django/lib/python2.5/django/template/debug.py", line 87, in render\n    output = force_unicode(self.filter_expression.resolve(context))\n  File "/home/gongura/webapps/django/lib/python2.5/django/template/__init__.py", line 559, in resolve\n    new_obj = func(obj, *arg_vals)\n  File "/home/gongura/webapps/django/lib/python2.5/django/template/defaultfilters.py", line 668, in date\n    return format(value, arg)\n  File "/home/gongura/webapps/django/lib/python2.5/django/utils/dateformat.py", line 264, in format\n    return df.format(format_string)\n  File "/home/gongura/webapps/django/lib/python2.5/django/utils/dateformat.py", line 29, in format\n    pieces.append(force_unicode(getattr(self, piece)()))\n  File "/home/gongura/webapps/django/lib/python2.5/django/utils/dateformat.py", line 174, in r\n    return self.format('D, j M Y H:i:s O')\n  File "/home/gongura/webapps/django/lib/python2.5/django/utils/dateformat.py", line 29, in format\n    pieces.append(force_unicode(getattr(self, piece)()))\n  File "/home/gongura/webapps/django/lib/python2.5/django/utils/encoding.py", line 49, in force_unicode\n    s = unicode(s)\n  File "/home/gongura/webapps/django/lib/python2.5/django/utils/functional.py", line 201, in __unicode_cast\n    return self.__func(*self.__args, **self.__kw)\n  File "/home/gongura/webapps/django/lib/python2.5/django/utils/translation/__init__.py", line 62, in ugettext\n    return real_ugettext(message)\n  File "/home/gongura/webapps/django/lib/python2.5/django/utils/translation/trans_real.py", line 290, in ugettext\n    return do_translate(message, 'ugettext')\n  File "/home/gongura/webapps/django/lib/python2.5/django/utils/translation/trans_real.py", line 280, in do_translate\n    _default = translation(settings.LANGUAGE_CODE)\n  File "/home/gongura/webapps/django/lib/python2.5/django/utils/translation/trans_real.py", line 198, in translation\n    default_translation = _fetch(settings.LANGUAGE_CODE)\n  File "/home/gongura/webapps/django/lib/python2.5/django/utils/translation/trans_real.py", line 181, in _fetch\n    app = getattr(__import__(appname[:p], {}, {}, [appname[p+1:]]), appname[p+1:])\nImportError: No module named syncr\n
[Mon Feb 02 14:49:21 2009] [notice] caught SIGTERM, shutting down
[Mon Feb 02 14:49:24 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Mon Feb 02 14:49:24 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Mon Feb 02 14:49:24 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Mon Feb 02 14:49:24 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Mon Feb 02 14:49:24 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Mon Feb 02 14:49:24 2009] [notice] mod_python: using mutex_directory /tmp 
[Mon Feb 02 14:49:24 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Mon Feb 02 14:49:25 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Mon Feb 02 15:03:20 2009] [notice] caught SIGTERM, shutting down
[Mon Feb 02 15:03:23 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Mon Feb 02 15:03:23 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Mon Feb 02 15:03:23 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Mon Feb 02 15:03:23 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Mon Feb 02 15:03:23 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Mon Feb 02 15:03:23 2009] [notice] mod_python: using mutex_directory /tmp 
[Mon Feb 02 15:03:23 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Mon Feb 02 15:03:24 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Thu Feb 05 16:08:28 2009] [notice] caught SIGTERM, shutting down
[Thu Feb 05 16:08:31 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Thu Feb 05 16:08:31 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Thu Feb 05 16:08:31 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Thu Feb 05 16:08:31 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Thu Feb 05 16:08:31 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Thu Feb 05 16:08:31 2009] [notice] mod_python: using mutex_directory /tmp 
[Thu Feb 05 16:08:31 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Thu Feb 05 16:08:32 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Thu Feb 05 16:23:33 2009] [notice] caught SIGTERM, shutting down
[Thu Feb 05 16:23:36 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Thu Feb 05 16:23:36 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Thu Feb 05 16:23:36 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Thu Feb 05 16:23:36 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Thu Feb 05 16:23:36 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Thu Feb 05 16:23:36 2009] [notice] mod_python: using mutex_directory /tmp 
[Thu Feb 05 16:23:36 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Thu Feb 05 16:23:37 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Thu Feb 05 18:16:47 2009] [notice] caught SIGTERM, shutting down
[Thu Feb 05 18:16:50 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Thu Feb 05 18:16:50 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Thu Feb 05 18:16:50 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Thu Feb 05 18:16:50 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Thu Feb 05 18:16:50 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Thu Feb 05 18:16:50 2009] [notice] mod_python: using mutex_directory /tmp 
[Thu Feb 05 18:16:50 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Thu Feb 05 18:16:51 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Thu Feb 05 18:21:18 2009] [notice] caught SIGTERM, shutting down
[Thu Feb 05 18:21:21 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Thu Feb 05 18:21:21 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Thu Feb 05 18:21:21 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Thu Feb 05 18:21:21 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Thu Feb 05 18:21:21 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Thu Feb 05 18:21:21 2009] [notice] mod_python: using mutex_directory /tmp 
[Thu Feb 05 18:21:21 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Thu Feb 05 18:21:22 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Thu Feb 05 22:49:11 2009] [notice] caught SIGTERM, shutting down
[Thu Feb 05 22:49:14 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Thu Feb 05 22:49:14 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Thu Feb 05 22:49:14 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Thu Feb 05 22:49:14 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Thu Feb 05 22:49:14 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Thu Feb 05 22:49:14 2009] [notice] mod_python: using mutex_directory /tmp 
[Thu Feb 05 22:49:15 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Thu Feb 05 22:49:16 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Thu Feb 05 22:51:16 2009] [notice] caught SIGTERM, shutting down
[Thu Feb 05 22:51:19 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Thu Feb 05 22:51:19 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Thu Feb 05 22:51:19 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Thu Feb 05 22:51:19 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Thu Feb 05 22:51:19 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Thu Feb 05 22:51:19 2009] [notice] mod_python: using mutex_directory /tmp 
[Thu Feb 05 22:51:19 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Thu Feb 05 22:51:20 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
[Thu Feb 05 22:51:57 2009] [notice] caught SIGTERM, shutting down
[Thu Feb 05 22:52:00 2009] [notice] SELinux policy enabled; httpd running as context user_u:system_r:unconfined_t
[Thu Feb 05 22:52:00 2009] [error] python_init: Python version mismatch, expected '2.5.1', found '2.5.2'.
[Thu Feb 05 22:52:00 2009] [error] python_init: Python executable found '/usr/local/bin/python'.
[Thu Feb 05 22:52:00 2009] [error] python_init: Python path being used '/home/gongura/webapps/django/lib/python2.5:/usr/local/lib/python25.zip:/usr/local/lib/python2.5/:/usr/local/lib/python2.5/plat-linux2:/usr/local/lib/python2.5/lib-tk:/usr/local/lib/python2.5/lib-dynload'.
[Thu Feb 05 22:52:00 2009] [notice] mod_python: Creating 2 session mutexes based on 2 max processes and 0 max threads.
[Thu Feb 05 22:52:00 2009] [notice] mod_python: using mutex_directory /tmp 
[Thu Feb 05 22:52:01 2009] [notice] Apache/2.2.3 (CentOS) mod_python/3.3.1 Python/2.5.2 configured -- resuming normal operations
[Thu Feb 05 22:52:02 2009] [error] server reached MaxClients setting, consider raising the MaxClients setting
